import { useEffect, useState, type ReactNode } from "react";
import { api } from "../lib/api.js";

const EFFECTIVE_DATE = "July 21, 2026";
const SUPPORT_EMAIL = (import.meta.env.VITE_SUPPORT_EMAIL as string | undefined)?.trim() || "support@forthebaddiez.com";
const OPERATOR_NAME = "Reginald Randolph";
const OPERATOR_ADDRESS = "2949 Parkwood Blvd, Frisco, TX 75034";

type LegalSection = { title: string; content: ReactNode };

const MOBILE_RETURN_PROTOCOLS = new Set(["personawrapper:", "exp:", "exps:"]);

export function legalMobileReturnHref(search: string): string | undefined {
  const returnTo = new URLSearchParams(search).get("returnTo");
  if (!returnTo) return undefined;
  try {
    const parsed = new URL(returnTo);
    return MOBILE_RETURN_PROTOCOLS.has(parsed.protocol) ? parsed.toString() : undefined;
  } catch {
    return undefined;
  }
}

const privacySections: LegalSection[] = [
  { title: "1. Scope and operator", content: <><p>This Privacy Policy explains how For the Baddiez collects, uses, discloses, retains, and protects information when you use our websites, mobile applications, APIs, persona-based chat experiences, and related support services (collectively, the “Service”). It applies to registered users, visitors, and people who contact support.</p><p>The Service is operated by {OPERATOR_NAME}, {OPERATOR_ADDRESS}. For purposes of applicable privacy law, {OPERATOR_NAME} is the person responsible for the personal information described in this policy.</p></> },
  { title: "2. Information you provide", content: <><p>We collect information you choose to provide, including:</p><ul><li>Account details such as email address, username, display name, profile image, password credential, and connected Google or Facebook account identifiers.</li><li>Conversation content, prompts, message history, feedback, persona selections, and feature preferences.</li><li>Files, images, documents, audio, microphone input converted to text, and other content you upload or generate.</li><li>ChatGPT, Claude, or other supported account-data archives you choose to import, including conversations and media contained in those archives.</li><li>Support communications, deletion requests, unsafe-output reports, intellectual-property complaints, and information needed to verify account ownership.</li></ul><p>Imported archives may contain information about other people. Only import an archive that belongs to you and that you are authorized to process. Passwords are stored as one-way password hashes. OAuth provider access tokens are not exposed to other users.</p></> },
  { title: "3. Information collected automatically", content: <p>We may automatically collect device and service information such as IP address, browser or app type, operating system, pseudonymous device or installation identifier, language, locale, time zone, current date and time, UTC offset, request timestamps, authentication events, crash information, diagnostic logs, feature usage, token usage, and approximate location inferred from network information. The current Service does not request or collect precise GPS location.</p> },
  { title: "4. Cookies, device storage, and telemetry", content: <><p>We use essential authentication cookies to keep users signed in and protect account sessions. The web application uses browser local storage for a pseudonymous installation identifier and session storage for interface state such as the selected conversation. The mobile application uses operating-system protected storage, such as SecureStore, for authentication state, selected conversation information, download-folder preferences, and application settings.</p><p>When telemetry is enabled, we may collect sampled application errors, rejected promises, rendering failures, API request timing, response status, page or route, trace identifiers, and related diagnostic details. We use this information to investigate failures, secure the Service, and measure reliability. We attempt to redact email addresses, credentials, access tokens, and other obvious secrets from client diagnostic messages before transmission. We do not currently use these technologies for third-party behavioral advertising.</p></> },
  { title: "5. AI processing", content: <><p>Your prompts, selected conversation context, and files may be sent to AI, speech, search, storage, and media-generation providers to produce requested responses. Files may be temporarily uploaded to provider systems for analysis, retrieval, code execution, image generation, file search, or other tools you request. Provider-side retention and permitted uses are governed by the applicable API or business terms, account settings, and service configuration and may differ from retention in our active systems.</p><p>AI output may be inaccurate, incomplete, offensive, or unsuitable for your circumstances. Do not submit secrets, highly sensitive personal data, protected health information, financial credentials, or information you do not have permission to process.</p></> },
  { title: "6. How we use information", content: <><ul><li>Provide, personalize, secure, and maintain the Service.</li><li>Authenticate users and synchronize chats across devices.</li><li>Generate persona responses, images, audio, files, analyses, and cited search results.</li><li>Import and export account archives at your direction and detect duplicate imported conversations.</li><li>Review unsafe-output reports, detect abuse, fraud, security incidents, and violations of our Terms.</li><li>Debug failures, monitor reliability, enforce usage limits, and improve product quality.</li><li>Respond to support, privacy, intellectual-property, and legal requests.</li><li>Comply with law and protect users, the public, and our rights.</li></ul><p>We do not sell personal information for money. We do not use your private conversation content for third-party advertising.</p></> },
  { title: "7. Service providers and disclosures", content: <><p>We use service providers to operate requested features and may disclose information to them as follows:</p><ul><li><strong>OpenAI:</strong> prompts, selected conversation context, uploaded files, images, and tool instructions for text generation, web search, file analysis, code execution, image generation, and related AI features.</li><li><strong>ElevenLabs:</strong> response or narration text, voice configuration, and technical request information needed to generate persona audio.</li><li><strong>Amazon Web Services and Amazon S3:</strong> uploaded files, generated media, data-transfer archives, object metadata, and technical storage records.</li><li><strong>Render:</strong> application, API, database, networking, and hosting information needed to run the Service.</li><li><strong>Google and Facebook OAuth:</strong> identifiers and profile information authorized by you, such as email address, name, and provider account identifier, for sign-in and connected-account management.</li><li><strong>Google Gmail SMTP:</strong> recipient email address, subject, message content, and delivery metadata for password resets, account notices, support, and other transactional email.</li><li><strong>Configured OpenTelemetry providers:</strong> operational metrics, traces, logs, route and response information, trace identifiers, performance measurements, and diagnostic error details when observability export is enabled.</li></ul><p>We may also disclose information to authorities when legally required; to protect safety, rights, or the Service; to investigate abuse or fraud; or as part of a merger, financing, acquisition, reorganization, or asset transfer subject to appropriate protections. We may share information at your direction, such as when you open a reference, share generated content, or connect a third-party account.</p></> },
  { title: "8. Retention schedule", content: <><p>We use the following retention approach, subject to legal holds, safety needs, disputes, and the configuration of the Service:</p><ul><li><strong>Accounts and chats:</strong> kept while the account is active, until you delete individual chats, or until the account-deletion process is completed.</li><li><strong>Uploads:</strong> kept while needed for the requested feature and then deleted at the configured expiration time; temporary uploads ordinarily have a shorter lifecycle than chats.</li><li><strong>Generated audio and media:</strong> kept until their configured expiration, deletion of associated data, or removal from active storage. Some deployments may retain generated media until the user deletes it.</li><li><strong>Provider files, vector stores, and processing artifacts:</strong> kept for the configured technical lifecycle or the provider’s applicable lifecycle, then deletion is requested where supported.</li><li><strong>Import files and downloadable export ZIPs:</strong> temporary job artifacts kept only through the configured download or processing window, ordinarily no longer than seven days and currently targeted for approximately 24 hours.</li><li><strong>Logs, telemetry, security, rate-limit, and spend records:</strong> kept for a limited operational, fraud-prevention, security, and accounting period, then deleted or aggregated.</li><li><strong>Unsafe-output reports, intellectual-property complaints, and enforcement records:</strong> kept as reasonably necessary to investigate, prevent repeat abuse, establish compliance, and resolve disputes; we may deidentify them where practical.</li><li><strong>Backups:</strong> retained according to encrypted backup-rotation schedules and allowed to age out; backups are used for disaster recovery rather than ordinary access.</li></ul><p>When account deletion is requested, access is disabled immediately and permanent deletion is scheduled after the recovery period in our Delete Account Policy. Deletion from active systems and service providers is initiated as part of the purge process. A provider may retain limited data where required by law, security obligations, or its applicable business terms.</p></> },
  { title: "9. Your choices and rights", content: <><p>You may access and update certain account information, delete individual chats, manage audio and device permissions, disconnect OAuth access through the provider, request an export, request account deletion, or restore a pending account before its deadline. Depending on where you live, you may also have rights to request access, correction, portability, restriction, objection, or deletion of personal data, and to appeal or complain to a regulator.</p><p>Submit requests through <a href="/support">Support</a>. We may verify your identity before acting and may deny or limit requests where permitted by law.</p></> },
  { title: "10. California privacy supplement", content: <><p>If California privacy law applies to you, the categories we may collect include identifiers, internet or electronic-network activity, account and service-usage information, user content, approximate location, and inferences used to operate or personalize the Service. We collect these categories from you, your device, connected sign-in providers, and service providers for the purposes in Sections 5 and 6. We disclose relevant categories to the providers in Section 7 for business purposes.</p><p>We do not sell personal information or share it for cross-context behavioral advertising. Subject to applicable exceptions, California residents may request to know, access, correct, delete, or receive a portable copy of covered information and may use an authorized agent. We will not discriminate against you for exercising a privacy right. Submit a request through Support and identify it as a California privacy request.</p></> },
  { title: "11. EEA and UK privacy supplement", content: <><p>{OPERATOR_NAME}, {OPERATOR_ADDRESS}, is the controller for personal data covered by this policy. We process account, chat, and requested feature data as necessary to perform our contract with you; security, reliability, support, abuse prevention, and product operations for our legitimate interests, balanced against your rights; optional permissions or features on consent where consent is required; and records necessary to comply with legal obligations. You may withdraw consent without affecting earlier lawful processing.</p><p>Recipients include the providers described in Section 7 and authorities or transaction parties in the limited circumstances described there. Data may be transferred to the United States and other countries using adequacy decisions, standard contractual clauses, the UK addendum or international data-transfer agreement, or another valid mechanism where required.</p><p>Subject to law, you may request access, correction, erasure, restriction, portability, or object to processing based on legitimate interests. You may complain to the supervisory authority where you live or work; UK users may contact the Information Commissioner’s Office. The Service does not use personal data to make solely automated decisions that produce legal or similarly significant effects. Retention is described in Section 8.</p></> },
  { title: "12. Security", content: <p>We use administrative, technical, and organizational safeguards designed to protect information, including hashed credentials, scoped authentication tokens, access controls, encrypted network transport in production, owner-based media authorization, and deletion workflows. No system is completely secure. You are responsible for protecting your credentials and promptly reporting suspected unauthorized access.</p> },
  { title: "13. Age requirement and children", content: <><p>You must be at least 16 years old to create an account or use the Service. Users who are 16 or 17 may use the Service only with permission from a parent or legal guardian.</p><p>The Service is not directed to children under 13, and we do not knowingly collect personal information from a child under 13. Contact Support if you believe a person under 16 has created an account or that a child has provided personal information. We may suspend the account and delete the associated information after appropriate verification.</p></> },
  { title: "14. International processing", content: <p>Information may be processed in the United States and other countries where our providers operate. Those locations may have different privacy laws. Where required, we use lawful transfer mechanisms and contractual protections as described in the EEA and UK supplement.</p> },
  { title: "15. Policy changes and contact", content: <><p>We may update this policy as the Service changes. Material changes will be communicated through the Service, email, or another appropriate channel before or when they take effect, and the effective date will be updated.</p><p>Privacy questions and requests may be sent to <a href={`mailto:${SUPPORT_EMAIL}?subject=Privacy request`}>{SUPPORT_EMAIL}</a> or mailed to {OPERATOR_NAME}, {OPERATOR_ADDRESS}.</p></> }
];

const termsSections: LegalSection[] = [
  { title: "1. Agreement", content: <p>These Terms of Use are a binding agreement between you and {OPERATOR_NAME}, the owner and operator of For the Baddiez, with a mailing address at {OPERATOR_ADDRESS}. By creating an account, accessing, or using the Service, you confirm that you are at least 16 years old and agree to these Terms and the Privacy Policy. If you are under 16 or do not agree, you may not create an account or use the Service.</p> },
  { title: "2. Eligibility and accounts", content: <><p>You must be 16 years of age or older to create an account or use the Service. If you are 16 or 17, you may use the Service only with permission from a parent or legal guardian. The Service may include strong language and mature themes. By registering or using the Service, you represent and warrant that you satisfy these requirements and are legally capable of entering this agreement.</p><p>You must provide accurate account information, keep credentials confidential, and promptly notify us of unauthorized access. You are responsible for activity under your account unless caused by our breach. You may not create accounts through automated means, impersonate another person, transfer credentials, or evade a suspension or usage restriction. We may suspend or delete an account if we reasonably believe the user is under 16 or provided false eligibility information.</p></> },
  { title: "3. The Service and personas", content: <><p>The Service provides fictional or stylized AI persona experiences. Personas, including names, voices, opinions, visual depictions, and responses, are generated or curated entertainment interfaces and are not real people, licensed professionals, or authoritative sources.</p><p>Personas are not intended to represent, portray, or identify any specific person, place, group, gang, or organization. Neither the personas nor the Service is affiliated with, endorsed by, sponsored by, or approved by any person, place, group, gang, or organization, except where we expressly identify a third-party service provider. References to third parties in user content or AI output do not imply any affiliation, endorsement, sponsorship, or approval.</p><p>We may add, modify, replace, or discontinue personas and features.</p></> },
  { title: "4. AI limitations", content: <><p>AI responses can be incorrect, outdated, biased, fabricated, or inconsistent. Search references can be incomplete or point to third-party content we do not control. Generated media may not meet your expectations. You must independently verify important information.</p><p>The Service is not a substitute for medical, legal, financial, mental-health, emergency, or other professional advice. Do not rely on it for high-impact decisions or emergencies.</p></> },
  { title: "5. Acceptable use and safety reports", content: <><p>You may not use the Service to:</p><ul><li>Break the law, violate another person’s rights, or facilitate fraud, harassment, exploitation, or violence.</li><li>Create or distribute child sexual abuse material, non-consensual intimate imagery, unlawful sexual content, or content that exploits minors.</li><li>Impersonate people deceptively, misrepresent generated content as authentic evidence, or interfere with elections or public safety.</li><li>Upload malware, steal credentials, bypass safeguards, probe systems without authorization, scrape at scale, or overload infrastructure.</li><li>Infringe copyrights, trademarks, privacy, publicity, confidentiality, or contractual rights.</li><li>Reverse engineer restricted components or resell access unless expressly authorized.</li></ul><p>Use the response actions in the app to report unsafe, unlawful, or seriously misleading AI output. You may also contact Support. We may investigate, restrict, remove content, suspend access, or preserve and disclose information where reasonably necessary to enforce these Terms or protect safety.</p></> },
  { title: "6. Your content, imports, and AI output", content: <><p>You retain rights you have in content you submit. You grant us a worldwide, non-exclusive, limited license to host, copy, process, transmit, transform, and display that content solely to operate, secure, support, and improve the Service and provide features you request. You represent that you have all rights and permissions needed for submitted content.</p><p>If you import a ChatGPT, Claude, or other supported account-data archive, you represent that the archive belongs to you or that you have permission from the account owner and every other person whose protected information it contains. You may not import another person’s account archive, private conversations, or media without authorization.</p><p>As between you and us, and to the extent permitted by law, you may use AI-generated output produced for you for lawful personal or commercial purposes. This permission does not transfer rights in third-party material or guarantee that an output is protectable, accurate, unique, or free of third-party copyrights, trademarks, privacy, publicity, or other rights. Other users may receive similar output. You are responsible for reviewing output before using or publishing it and for obtaining any permission your use requires.</p></> },
  { title: "7. Our intellectual property", content: <p>The Service, application design, branding, logos, software, persona configuration, and other materials we provide are owned by us or our licensors and protected by intellectual-property laws. Except for the limited right to use the Service under these Terms, no rights are transferred to you.</p> },
  { title: "8. Intellectual-property complaints", content: <><p>If you believe content available through the Service infringes your copyright, trademark, or another intellectual-property right, send a takedown request to <a href={`mailto:${SUPPORT_EMAIL}?subject=Intellectual-property complaint`}>{SUPPORT_EMAIL}</a>. Include your name and contact information; identification of the protected work or right; the specific content, conversation, output, or location at issue; a statement of your good-faith belief that the use is unauthorized; a statement that the information is accurate and that you are authorized to act; and your physical or electronic signature.</p><p>We may request more information, remove or restrict content, notify the affected user, and terminate repeat infringers where appropriate. Knowingly submitting a false complaint may create liability. A user who believes content was removed by mistake may contact the same address with supporting information.</p></> },
  { title: "9. Third-party services and Apple license", content: <><p>The Service may depend on or link to third-party platforms, models, websites, app stores, and OAuth providers. Their terms and privacy practices apply to their services. We are not responsible for third-party content, availability, or conduct.</p><p>If you download the iOS application through Apple’s App Store, Apple’s <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noreferrer">Standard Licensed Application End User License Agreement</a> applies to the application license in addition to these Terms. If those terms conflict solely as to the App Store application license, Apple’s standard EULA controls. These Terms remain between you and {OPERATOR_NAME}; Apple is not responsible for the Service.</p></> },
  { title: "10. Availability, changes, and beta features", content: <p>We may change, limit, suspend, or discontinue all or part of the Service. Features may be experimental and may fail, lose state, or change without notice. We do not promise uninterrupted availability, preservation of every output, or compatibility with every device.</p> },
  { title: "11. Suspension and termination", content: <p>You may stop using the Service or request account deletion at any time. We may suspend or terminate access for violations, security risk, legal requirements, nonpayment where applicable, or material harm. Sections that by nature should survive termination remain effective, including ownership, complaints, disclaimers, limitations, and dispute terms.</p> },
  { title: "12. Disclaimers", content: <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE.” WE DISCLAIM IMPLIED WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, AND QUIET ENJOYMENT. SOME JURISDICTIONS DO NOT ALLOW CERTAIN DISCLAIMERS, SO THESE LIMITATIONS MAY NOT FULLY APPLY TO YOU.</p> },
  { title: "13. Limitation of liability", content: <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR LOST PROFITS, DATA, GOODWILL, OR OPPORTUNITIES ARISING FROM THE SERVICE. OUR AGGREGATE LIABILITY FOR CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED THE GREATER OF THE AMOUNT YOU PAID US FOR THE SERVICE DURING THE 12 MONTHS BEFORE THE CLAIM OR US$100. RIGHTS THAT CANNOT LAWFULLY BE LIMITED REMAIN UNAFFECTED.</p> },
  { title: "14. Indemnity", content: <p>To the extent permitted by law, you agree to defend, indemnify, and hold us harmless from claims, losses, and expenses arising from your unlawful use of the Service, your content, unauthorized imports, or your material breach of these Terms. This does not apply where prohibited or to losses caused by our own misconduct.</p> },
  { title: "15. Disputes and governing terms", content: <p>Before filing a formal claim, contact Support and allow 30 days for an informal resolution. These Terms and claims relating to the Service are governed by the laws of the State of Texas and applicable federal laws of the United States, without regard to conflict-of-law rules. Subject to mandatory consumer protections that cannot lawfully be waived, you and {OPERATOR_NAME} consent to the jurisdiction of state and federal courts located in Texas.</p> },
  { title: "16. Changes to these Terms", content: <><p>We may update these Terms to reflect changes to the Service, law, security, providers, or business practices. The effective date at the top identifies the current version. For material changes, we will provide reasonable notice through the Service, email, or another appropriate channel before or when the changes take effect.</p><p>If you do not agree to revised Terms, you must stop using the Service before they take effect and may request account deletion. Your continued use after the effective date constitutes acceptance where permitted by law. We will obtain affirmative consent when applicable law requires it, and changes will not retroactively alter rights or obligations that already accrued unless law permits and the notice clearly says so.</p></> },
  { title: "17. General", content: <p>If a provision is unenforceable, the remaining provisions remain in effect. Failure to enforce a provision is not a waiver. You may not assign these Terms without consent; we may assign them in connection with a reorganization or transfer of the Service. These Terms, the Privacy Policy, Apple’s standard EULA where applicable, and incorporated policies are the entire agreement concerning the Service.</p> },
  { title: "18. Contact", content: <p>Questions about these Terms may be sent to <a href={`mailto:${SUPPORT_EMAIL}?subject=Terms of Use question`}>{SUPPORT_EMAIL}</a> or mailed to {OPERATOR_NAME}, {OPERATOR_ADDRESS}.</p> }
];

const deletionSections: LegalSection[] = [
  { title: "How to request deletion", content: <><p>Signed-in users can open <strong>Settings → Account → Delete account</strong> on web, iOS, or Android. Password accounts must enter their password and type <strong>DELETE</strong>. OAuth-only users confirm through their authenticated session. You may also use the secure request form below or contact <a href="/support">Support</a> if you cannot access your account.</p></> },
  { title: "What happens immediately", content: <ul><li>Your account status changes to pending deletion.</li><li>All active sessions and refresh tokens are revoked.</li><li>You are signed out and normal account access is blocked.</li><li>Your scheduled permanent-deletion date is shown after confirmation.</li></ul> },
  { title: "30-day recovery period", content: <p>Permanent deletion is scheduled 30 days after the request. Before that deadline, password users can choose <strong>Restore account</strong> and authenticate again. OAuth users can sign in with the same connected provider to restore. Restoration reactivates the account and cancels the pending purge. After the deadline, restoration is unavailable.</p> },
  { title: "Data permanently deleted", content: <><p>The purge is designed to delete the user record, password credential, OAuth identities, sessions, conversations, messages, uploads, generated images and files, generated audio, OpenAI artifacts and vector stores, background jobs, and account-linked usage records. Running jobs are cancelled first to prevent them from recreating data after deletion.</p><p>Deletion requests sent to storage and AI providers may be retried if a provider is temporarily unavailable. Limited records may be retained where legally required or reasonably necessary for security, fraud prevention, dispute resolution, or enforcement. Residual encrypted backups age out under backup rotation and are not returned to active service.</p></> },
  { title: "Subscriptions and third-party accounts", content: <p>Deleting your For the Baddiez account does not automatically cancel an Apple App Store, Google Play, or other third-party subscription unless the applicable store confirms otherwise. Cancel subscriptions through the store before deletion. Deleting your account also does not delete your Google or Facebook account; you can separately revoke For the Baddiez access in that provider’s settings.</p> },
  { title: "Identity verification and support requests", content: <p>To protect users, we may require authentication or reasonable proof of account ownership. Do not email your password. Support may ask for the account email, username, OAuth provider, approximate creation date, or other non-secret information. We will never ask for a password, access token, or one-time authentication code.</p> }
];

function PageFrame({ title, eyebrow, intro, sections, children }: { title: string; eyebrow: string; intro: string; sections: LegalSection[]; children?: ReactNode }) {
  const mobileReturnHref = legalMobileReturnHref(window.location.search);
  const mobileReturnQuery = mobileReturnHref ? `?returnTo=${encodeURIComponent(mobileReturnHref)}` : "";
  const publicPageHref = (path: string) => `${path}${mobileReturnQuery}`;

  function handleBack(event: React.MouseEvent<HTMLAnchorElement>): void {
    if (mobileReturnHref) return;
    let cameFromThisApp = false;
    try {
      cameFromThisApp = Boolean(document.referrer) && new URL(document.referrer).origin === window.location.origin;
    } catch {
      cameFromThisApp = false;
    }
    if (!cameFromThisApp || window.history.length <= 1) return;
    event.preventDefault();
    window.history.back();
  }

  return <main className="legal-shell">
    <header className="legal-header">
      <div className="legal-header-brand-group">
        <a className="legal-back-link" href={mobileReturnHref ?? "/"} onClick={handleBack} aria-label="Back to For the Baddiez">← Back</a>
        <a className="legal-brand" href={mobileReturnHref ?? "/"} aria-label="For the Baddiez home"><img src="/FTB_logo/For_the_Baddiez_logo_transparent.png" alt="" /><span>For the Baddiez</span></a>
      </div>
      <nav aria-label="Legal and support"><a href={publicPageHref("/privacy")}>Privacy</a><a href={publicPageHref("/terms")}>Terms</a><a href={publicPageHref("/delete-account")}>Delete account</a><a href={publicPageHref("/support")}>Support</a></nav>
    </header>
    <article className="legal-document">
      <div className="legal-hero"><p className="legal-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p><span>Effective {EFFECTIVE_DATE}</span></div>
      {children}
      <div className="legal-sections">{sections.map((section) => <section key={section.title} id={section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}><h2>{section.title}</h2>{section.content}</section>)}</div>
    </article>
    <footer className="legal-footer"><span>© {new Date().getFullYear()} For the Baddiez</span><a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a></footer>
  </main>;
}

function DeleteAccountRequestForm() {
  const [identifier, setIdentifier] = useState("");
  const [password, setPassword] = useState("");
  const [confirmation, setConfirmation] = useState("");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string>();
  const [authenticated, setAuthenticated] = useState(false);

  async function authenticate() {
    setBusy(true); setMessage(undefined);
    try { await api.login({ identifier: identifier.trim(), password, clientType: "web" }); setAuthenticated(true); setMessage("Identity verified. Type DELETE to schedule permanent deletion."); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Could not verify this account."); }
    finally { setBusy(false); }
  }
  async function remove() {
    if (confirmation !== "DELETE") return;
    setBusy(true); setMessage(undefined);
    try { const result = await api.deleteAccount({ confirmation: "DELETE", password }); setAuthenticated(false); setPassword(""); setConfirmation(""); setMessage(`Deletion scheduled for ${new Date(result.deletionScheduledFor).toLocaleDateString()}. Sign in and choose Restore account before that date to cancel.`); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Could not schedule deletion."); }
    finally { setBusy(false); }
  }
  return <section className="legal-action-panel" aria-labelledby="delete-request-title"><p className="legal-eyebrow">Secure request</p><h2 id="delete-request-title">Request account deletion</h2><p>Password accounts can complete the request here. OAuth-only users should use in-app Settings or contact Support from the email associated with the account.</p><label>Email or username<input value={identifier} onChange={(event) => setIdentifier(event.target.value)} disabled={busy || authenticated} autoComplete="username" /></label><label>Password<input value={password} onChange={(event) => setPassword(event.target.value)} disabled={busy || authenticated} type="password" autoComplete="current-password" /></label>{authenticated ? <label>Confirmation<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} disabled={busy} placeholder="Type DELETE" /></label> : null}{message ? <p className="legal-form-message" role="status">{message}</p> : null}<button type="button" disabled={busy || !identifier.trim() || !password || (authenticated && confirmation !== "DELETE")} onClick={() => void (authenticated ? remove() : authenticate())}>{busy ? "Please wait..." : authenticated ? "Schedule account deletion" : "Verify account"}</button></section>;
}

export function PublicLegalPage({ path }: { path: string }) {
  useEffect(() => {
    const titles: Record<string, string> = {
      "/privacy": "Privacy Policy",
      "/terms": "Terms of Use",
      "/delete-account": "Delete Account Policy",
      "/support": "Support"
    };
    document.title = `${titles[path] ?? "Legal"} | For the Baddiez`;
    return () => { document.title = "For the Baddiez"; };
  }, [path]);

  if (path === "/privacy") return <PageFrame eyebrow="Legal" title="Privacy Policy" intro="How information is handled across For the Baddiez chat, persona, media, voice, and support experiences." sections={privacySections} />;
  if (path === "/terms") return <PageFrame eyebrow="Legal" title="Terms of Use" intro="The rules, responsibilities, and limitations that apply when using For the Baddiez." sections={termsSections} />;
  if (path === "/delete-account") return <PageFrame eyebrow="Account control" title="Delete Account Policy" intro="How to request deletion, restore during the recovery window, and understand what is permanently removed." sections={deletionSections}><DeleteAccountRequestForm /></PageFrame>;
  return <PageFrame eyebrow="Help center" title="Support" intro="Get help with accounts, sign-in, privacy, deletion, chats, generated content, audio, and mobile app issues." sections={[
    { title: "Contact support", content: <><p>Email <a href={`mailto:${SUPPORT_EMAIL}?subject=For the Baddiez support request`}>{SUPPORT_EMAIL}</a>. Include the account email or username, platform (web, iOS, or Android), app version, what you expected, what occurred, and non-sensitive screenshots or error text.</p><p>Never send your password, access token, OAuth code, payment card details, or government identification unless support provides a verified secure process that specifically requires it.</p></> },
    { title: "Account and sign-in help", content: <p>For password issues, confirm the exact email or username and check capitalization. For Google or Facebook sign-in, use the same provider originally connected to the account. A pending-deletion account must be restored before normal sign-in. If the recovery deadline passed, the old account cannot be restored, but you may create a new account.</p> },
    { title: "Deletion and privacy requests", content: <p>Use the <a href="/delete-account">Delete Account page</a> for account deletion. For access, correction, portability, objection, or other privacy requests, email Support with “Privacy request” in the subject. We may verify account ownership before acting.</p> },
    { title: "AI output and safety reports", content: <p>AI can make mistakes. Report harmful, infringing, impersonating, unsafe, or clearly incorrect output with the conversation date, persona, prompt context, and a description of the concern. Do not forward unlawful content by email; describe it and wait for secure instructions.</p> },
    { title: "Generated media, audio, and downloads", content: <p>For missing images or audio, keep the conversation available and include the approximate request time. Mobile downloads require operating-system media permissions. Speech-to-text requires microphone and speech-recognition permissions. Simulator behavior can differ from a physical device.</p> },
    { title: "Security reports", content: <p>Report suspected account compromise or vulnerabilities promptly with reproducible steps and impact. Do not access other users’ data, disrupt production, or publish sensitive findings before we have a reasonable opportunity to investigate.</p> },
    { title: "Response expectations", content: <p>We prioritize account security, deletion, privacy, and safety reports. Response times vary by complexity and volume. Sending duplicate requests can delay investigation. Keep your support ticket and reply in the same email thread.</p> }
  ]} />;
}

export const PUBLIC_PAGE_PATHS = new Set(["/privacy", "/terms", "/delete-account", "/support"]);
